datadog-plugin: Set metrics.required to be false
The DataDog plugin is configured to set `DEFAULT_METRICS`; meaning you don't by default have to manually configure any metrics to send to DataDog. However, when the schema sets `required = true` alongside a default value, the Admissions Controller will fail with the following error if no metrics are provided: 

Error: UPGRADE FAILED: cannot patch "global-datadog" with kind KongClusterPlugin: admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.metrics: required field missing)

In order to use the default DataDog metrics values and the Admissions Controller in parallel, this value needs to be false.